### ISSUE TITLE
OutOfMemoryError is swallow and can lead to an incomplete comparison

### ISSUE THREAD

**Issue by FaustXVI** [red6/pdfcompare#75] opened 2020-07-03 08:21 UTC
I am using pdfcompare for testing PPT generation. I first generate PDF from PPT then use pdfcompare to check expected rendering.

While comparing two 15 pages pdf with a limit of 512Mb (default conf of gradle) that I know were different my test was passing.
After investigation, the code correctly compare the first page (which were correct) and stopped comparing because of `OutOfMemoryError`s.
The error should be reproduced with any two different PDF by limiting the VM memory enough using the `-Xmx` option.

Here is my analysis : 

The error is throw in an executor name `parrallelDrawExecutor` that is used in the `drawImage` method : 
https://github.com/red6/pdfcompare/blob/8e52231888158fc5e795a29f768dbdfefafef767/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L416

This will trigger an `ExecutionException` that is catch in the `getImage` method : 
https://github.com/red6/pdfcompare/blob/8e52231888158fc5e795a29f768dbdfefafef767/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L443

It is then translated to a `RenderingException` on the next line : 
https://github.com/red6/pdfcompare/blob/8e52231888158fc5e795a29f768dbdfefafef767/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L446

This exception is catched and ignored (swallowed) in the `drawImage` method : 
https://github.com/red6/pdfcompare/blob/8e52231888158fc5e795a29f768dbdfefafef767/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L428

The consequence is that no `DiffImage` is created, so no comparison is made and so no difference is found.
The error being swallowed, it's totally invisible to the user and thus can be misleading.

The way I would (naively) fix it : 
I think that a rendering error is a deal breaker for the compare method so I would like to let the exception bubble up.
Since this is a public library, I also would like to not change the signature of the compare method.
Thus letting the `RenderingException` bubble up as is is not an option but wrapping it in a `RuntimeException` would work.

Further improvement options : 
Since the exception will bubble up, it's important to not loose the origin of it (the `OutOfMemoryException`) so that the user can understand what's happening.
Thus I would move (and duplicate) the creation of the `RenderingException` in each catch so that we can pass the original exception (the cause) to the constructor.

I'd be happy to make a PR to fix this issue.

**Comment by finsterwalder** [comment] 2020-07-03 17:24
Thanks for this detailed analysis.
You are totally right. Swallowing the cause is a bad idea and swallowing the exception even more so.
BTW: RenderingException is already a RuntimeException, so it could be propagated.
The real problem is, how is the exception propagated across threads. An exception in another thread is not propagated but only crashes that thread.
I just release a new version (1.1.51), that propagates exceptions and renders a page with the exception.
And I also log an error level message. The exception is not yet propagated to the main thread. Maybe that's another idea to follow....
But please try the new version and tell me, whether that is helpful.

**Comment by finsterwalder** [comment] 2020-07-05 17:11
I added some code to propagate exceptions from other executors back to the main thread and throw a RenderingException with all the Exceptions from other thread added as SuppressedExceptions. Maybe that's bette?
Check out version 1.1.52

**Comment by FaustXVI** [comment] 2020-07-07 09:01
The `ExecutionException` is the exception that propagates the threads exception : https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutionException.html
You should not have to add any code except not swallowing the `ExecutionException`.
Maybe you already knew that and I misunderstood your previous messages. Maybe you didn't and it should help you to write a simpler code :)

**Comment by FaustXVI** [comment] 2020-07-07 09:13
I just read the code you wrote and I confirm my previous message : you should not need this i think.
But if you do, please know that ArrayList is *not* thread safe : 
https://github.com/red6/pdfcompare/blob/edef7ede16a09cbfe8cb5ed976bc29cba38c45a8/src/main/java/de/redsix/pdfcompare/PdfComparator.java#L67
This mean you have a race condition. It is *super* hard to debug because it's hard to reproduce. The only thread safe list in the sdk is `CopyOnWriteArrayList` : https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html
If performance is an issue for you, using a queue could be an option.

I just realized that I talk a lot about issues but please keep in mind that your code helps me a *LOT* in my day to day work. Thanks a lot for your awesome work !

**Comment by finsterwalder** [comment] 2020-07-07 14:33
Thanks for the hint regarding ArrayList not being thread safe. I didn't think about that. I will correct that.
Regarding ExecutionException: As far as I understand, they only work "out of the box" with things like Futures. We don't have a Future to transfer Information between the main thread and the Executor worker threads. That's why we need something different. How else is the JVM supposed to know where to send the ExecutionException to?

**Comment by finsterwalder** [comment] 2020-07-07 15:22
Check out Version 1.1.53.
Does that close this issue for you?

**Comment by FaustXVI** [comment] 2020-07-07 16:06
I looks like it does solve my issue indeed :) Thanks :)
I missed that you were executing it in another thread (there is two levels of executors and missed one) in which you don't have a Future.
Since I am always uncomfortable when I see multi-threaded code (that's too hard for me) I tends to avoid it as much as possible. After skimming the code, I didn't see any issues. If it was my code, I would probably try to get futures from that executor so that thread handling code is not my code :)
I wish I had more time to dedicate to you and contribute more :(
Cheers

**Comment by finsterwalder** [comment] 2020-07-07 16:12
I will close the ticket then.
I think doing the latch countdown and awaiting that is better than handling some kind of Future, even though I don't expect a result.
That's not too tricky, I think.
But yes, threading can be hard on your brain... ;-)

**Closed by finsterwalder** 2020-07-07 16:12 UTC
