### ISSUE TITLE
WARN de.redsix.pdfcompare.PdfComparator - No files found to compare

### ISSUE THREAD

**Issue by SMVignesh** [red6/pdfcompare#36] opened 2018-08-01 08:57 UTC
Hi,

I'm getting the following message "WARN de.redsix.pdfcompare.PdfComparator - No files found to compare" even the PDF files were present in the path specified.

*Following is my piece of code to compare two sample PDF's:

package PDFcomparison;

import de.redsix.pdfcompare.PdfComparator;

public class pdfcomparisontest {

	public static void main(String[] args) throws Exception {
		
		String requirement = "D:\\PDFComparisonPDFs\\doc1.pdf";
		String actual = "D:\\PDFComparisonPDFs\\doc2.pdf";
		String results = "D:\\PDFComparisonPDFs\\Results\\output";
		new PdfComparator(requirement, actual).compare().writeTo(results);
		System.out.println("Completed");

	}

}

Following is the dependencies added to POM.xml

<dependencies>
  <dependency>
    <groupId>de.redsix</groupId>
    <artifactId>pdfcompare</artifactId>
    <version>1.1.25</version> 
  </dependency>
</dependencies>

**Comment by rweisleder** [comment] 2018-08-08 15:06
I tried to reproduce your issue with this snippet:
```java
public static void main(String[] args) throws Exception {
    String requirement = "D:\\PDFComparisonPDFs\\doc1.pdf";
    String actual = "D:\\PDFComparisonPDFs\\doc2.pdf";

    createDummyFile(requirement);
    createDummyFile(actual);

    new PdfComparator(requirement, actual).compare();
    System.out.println("Completed");
}

private static void createDummyFile(String pathname) throws Exception {
    new File(pathname).getParentFile().mkdirs();
    try (FileOutputStream outputStream = new FileOutputStream(pathname)) {
        outputStream.write("Hello World".getBytes());
    }
}
```

This doesn't log "No files found to compare". (Instead it throws an Exception because my files are no pdf files obviously.) So I'm inclined to say that your specified file are really not there.

**Comment by finsterwalder** [comment] 2018-08-15 13:42
I close this, since I have no idea, how we could help. If your problem persists, please reopen the issue with your explanaition.

**Closed by finsterwalder** 2018-08-15 13:42 UTC

**Comment by sankalprao** [comment] 2021-04-09 02:57
@rweisleder I am getting this same very issue. When I compare the code you tried to reproduce the issue from the one who reported, you are not using the method writeTo(). When we invoke this method, I am getting the same error. Can you kindly reopen this issue please and provide a fix?
